### ISSUE TITLE
We need axis individual deadzone(axis, stick)

### ISSUE THREAD

**Issue by tooOpen** [Unity-Technologies/InputSystem#1052]
What's up
First thank you for Unity2019.3
Now I use new InputSystem and I'm in trouble.
I want to use deadzone because I don't need little value
ex) (1.0, 0.1)  -> (1.0, 0) 
like above
but current deadzone only check magnitude value(I think)
so I need each axis deadzone 
I mean even x aixs value 1.0 though if y axis value is 0.1, It should be zero.
if this function already exist please let me know.

Thank you for good new system.

**Comment by Rene-Damm** [comment]
Not sure there is a good way to make this change to `StickDeadzoneprocessor`. The current deadzoning does indeed operate on magnitude which indeed means that as long as one axis crosses the magnitude threshold, the resulting vector will move out of the deadzone -- even if one axis is indeed below the deadzone threshold.

However, if that wasn't the case, you'd no longer cull just below min and above max threshold, but you'd rather cull an entire slice extending along each axis. I.e. instead of the situation depicted here on the left, you'd now get the situation on the right.

![image](https://user-images.githubusercontent.com/3418347/74359912-69ab8a80-4dc4-11ea-9480-69c353cecbc9.png)

The current deadzone processor renormalizes within the clipped space so that you get a continuous [0..1] space in-between [min..max]. If each axis is clipped individually, the processor would in addition have to renormalize within each quadrant to make the value space continuous again.

Could be done but not sure this is indeed a good thing.

As for axes, these are indeed deadzoned individually. For example, `gamepad.leftStick.x.ReadValue()` is not the same as `gamepad.leftStick.ReadValue().x` but rather an individually, non-radially deadzoned value.

Reading X and Y out individually may give you what you're looking for. In the upcoming 1.0.0-preview.5 you will also have the ability to set up Vector2 composite to analog mode and thus bind it to a stick's up/down/left/right controls individually.

////EDIT: Technically, the "cull an entire slice extending along each axis" thing isn't 100% correct as the vector along each axis itself would still come through. Just around that on each side would be a slice that disappears.

**Comment by tooOpen** [comment]
thank you @Rene-Damm

**Comment by W4RH4WK** [comment]
Hey, I just ran into this where I have a Vector2 input which is bound to a stick, but I don't want to use a radial deadzone.

Interestingly I found a workaround that might not be intended.
My Action is set to be a Vector2 and instead of binding a stick directly, I chose to bind it as a composite, with mode set to analog and a stick deadzone attached.

![image](https://user-images.githubusercontent.com/328798/94577119-7955e180-0276-11eb-8472-7116a86fa9a9.png)

When I move the stick straight upwards (Y direction), the X axis is still deadzoned.
