### ISSUE TITLE
Button Input Sends input twice for every press

### ISSUE THREAD

**Issue by AutumnEvans418** [Unity-Technologies/InputSystem#1089]
I have this input setup for jump
![image](https://user-images.githubusercontent.com/33850520/76682961-57dd2300-65ce-11ea-97d4-e9d5234b09d9.png)

And have it on this object:
![image](https://user-images.githubusercontent.com/33850520/76682975-66c3d580-65ce-11ea-8f78-c80f5bd12a35.png)

However, no matter what I do, the button always sends two events for every jump.  What setting am I missing?

**Comment by LaviMahal** [comment]
Same with me, works fine if I set behavior to Send Message but using Unity Events, its always calling the method 3 times.

**Comment by Rene-Damm** [comment]
This is by design. The current setup uses a simplified callback system when using messages but exposes the UnityEvent callbacks to the full started/performed/canceled style of actions. I.e. you get a callback when the action starts, when it cancels, and when it performs. You can check which it is by checking `InputAction.CallbackContext.phase` or using the structs `started`, `performed`, and `canceled` properties.

Has been confusing to a number of people. Making this more streamlined and obvious is on the list.
