### ISSUE TITLE
Not registering any delta mouse movements when cursor is locked

### ISSUE THREAD

**Issue by muisje** [Unity-Technologies/InputSystem#1149]
As the title says the delta value of the mouse stays zero when moving the mouse and the cursor is locked. Unlocked delta has value when moving the mouse. 

This issue occurs on my machine with ubuntu, but on windows it seems to work fine.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

The issue is now being tracked at https://issuetracker.unity3d.com/product/unity/issues/guid/1248389/ 

For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
