### ISSUE TITLE
leftStick is deadzoned but leftStick/x and leftStick/y individually aren't

### ISSUE THREAD

**Issue by todi1856** [Unity-Technologies/InputSystem#125]
Adding a note just in case:

Suppose there is this input control 
[InputControl(processors = "PositionTransform")] public Vector2 position;

If you'll access control like this 

position.ReadValue() - everything is good PositionTransform processor will process the value

but if you'll access values like this

position.y.ReadValue() - PositionTransform won't be applied, this is not very intuitive.

Some kind of resolution must be taken.

**Comment by Rene-Damm** [comment]
Yeah, not sure yet what to do about this one. The current behavior is surprising which rarely is a good quality.

One possible solution (and something that can be done with functionality that already exists) is to require layouts to deal with that manually. For example, if you put a deadzone processor on the stick, then you also need to put processors on X and Y individually. However, that would also require changing `Vector2Control` to read raw values from X and Y instead of processed values or you get double processing.

The other solution would be to make this automatic and have the system automatically check parent controls (which, however, then has to crawl up the entire tree -- sucks). However, that's somewhat tricky. How would the system know what to do with the Vector2 from `leftStick`? How would it even know which value type to deal with? `Vector2Control` knows how to combine X and Y. So it seems that to make this work, it would also have to expose a way to break it back down into X and Y after processing.

So yeah, not sure. Those two solutions both seem very ugly to me. Hopefully there's a better one that I'm just not seeing.

**Comment by Baste-RainGames** [comment]
Just wanted to pipe in and say that it took me about half an hour to figure this out. It's _super_-confusing.

Does Vector2Control really need x and y that's not just property-wrappers around ReadValue().x and ReadValue().y? I'm getting a Vector2 from ReadValue, a different way of accessing that doesn't really feel neccessary.
I would want to be able to access the raw values of the controller, but ReadValueRaw seems like the comfortable way to get that.

**Comment by hippocoder** [comment]
+1 Totally baffling, and I would repeatedly get confused on account of not being as bright as my peers :)

**Comment by Rene-Damm** [comment]
Closing this. Was fixed some time ago by having axis deadzone processors added automatically to the individual stick axes.
