### ISSUE TITLE
[Windows] [Keyboard] When numlock is released, pressing arrow key triggers Print Screen key.

### ISSUE THREAD

**Issue by JiaUnity** [Unity-Technologies/InputSystem#142]
When the Numlock is not in effect and the number pad does not work as number input, pressing the arrow keys also triggers Print Screen key.
![printscreen](https://user-images.githubusercontent.com/33637761/41484821-1da67466-7093-11e8-974b-6b3cd99e9607.gif)

**Comment by douglas-piconi** [comment]
I can reproduce 100% of time.    Taking a look at fix.

**Comment by douglas-piconi** [comment]
![bits](https://user-images.githubusercontent.com/24575155/42841316-a2fe2ce6-89d7-11e8-98a9-2310791cf63f.png)

doesnt matter id NumLock was on or off when started, if it is hit, then anytime you press any of arrow, or INS. HOME, etc...   you get a state buffer with two bits set, and one of them is PrtScn.   This happens in both Editor and Standalone player mode.

**Comment by douglas-piconi** [comment]
ok tracked this down to the native windows scan codes.  This appears to be what microsoft is sending.  If the num lock is off it will send 2 scan codes and prtscn could be one of them 0xE02A

Insert, Delete, Home, End, Page Up, Page Down, Up, Down, Left, Right: when Num Lock is on or one or both shift keys are pressed, 0xE02A, 0xE0AA, 0xE036, 0xE0B6 can be as postfix or prefix

Looks like not a bug and this is by design from microsoft.

**Comment by JiaUnity** [comment]
This is by design on the MS part.
