### ISSUE TITLE
Input Actions weird states

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#18]
Create an Input Actions asset and setting it with certain empty parameters results in errors and invalid object states

(1) Having 1 action set with no actions and hitting "apply" results in a TreeView error related to having null children.  The empty action set will be shown, but is not interact-able until you add a new set, which seems to overwrite the previous empty default set.
(2) Create only one action set and create an action with no bindings, then hit apply.  Then delete the single action set.  There is an error about an array property that has disappeared and pushing more GUIClips than you are popping.  Scrolling the mouse wheel at this point results in the GUIClips error repeating.  The Input Action Inspector UI also changes, with the layout changing slightly and "Imported Object" text appearing at the bottom of the UI.
(3) Create an action set, add a single action bound to "ByUsage/Accept" and hit apply.  The "Generate C# Wrapper Class" checkbox and "revert" and "apply" buttons disappear.  There is an error related to an operation not being valid due to the current state of the object.  This seems to fire as the mouse is moved in and out of the Input Action inspector view, or when the mouse wheel is scrolled.  At this stage, changing the single binding to, say, "gamepad/buttonEast" returns the wrapper class checkbox and revert/apply buttons, but the buttons are greyed out.

**Comment by Rene-Damm** [comment]
1. On head, will not result in exception but empty action sets will mysteriously disappear. The reason is that the underlying serialization format has no concept of action sets but rather makes sets implicit in action names (i.e. "gameplay/fire" => action "fire" in set "gameplay). Probably should be changed. Leaving this for later.

2. Fixed as of 330b215d4a0ed79c23c0d88b4322bcf342aa4cdf.

3. Same.

So at least as far as exceptions go, things should work on current head.
