### ISSUE TITLE
Hold interaction doesn't use its "repeat" parameter

### ISSUE THREAD

**Issue by wendelscardua** [Unity-Technologies/InputSystem#226]
Line 15 of HoldInteraction.cs seems to be the only occurrence of "repeat" in a C# file

**Comment by Rene-Damm** [comment]
The interactions overall need a pass on them to ensure the set makes sense and each one covers the ground it's supposed to. There's still a number of loose ends to tie up there.

**Comment by PlanetVaster** [comment]
This seems to still not be fixed.

**Comment by gorxmedia** [comment]
Confirming its still borked.

**Comment by JiaUnity** [comment]
This should be fixed in the past updates. Instead of repeat, using "InputAction.continuous = true" to achieve the same effect.
If there is any more issue, please feel free to file bug through Bug Reporter in Editor. With the help of a minimum repro project, we'll be able to identify and resolve issues sooner.
