### ISSUE TITLE
[MacOS Standalone] InputSystem.devices contains no devices in MacOS standalone build.

### ISSUE THREAD

**Issue by gmiot-poc** [Unity-Technologies/InputSystem#244]
InputSystem.devices contains no input devices in MacOS standalone build.
Neither does InputSystem.GetUnsupportedDevices().

-It works in Unity Editor, on mac OS, i can access and see all the plugged devices.
-Unity version is 2018.2.6.f1.
-Package version is 0.0.6. 
-I'm using the demo provided with the package. 
-It works fine on Windows (Unity Editor and standalone build).
-Specs : 

![mac](https://user-images.githubusercontent.com/17002338/45211345-5375d280-b292-11e8-9230-acc2530f2e4b.JPG)

**Comment by douglas-piconi** [comment]
@gmiot-poc  Due to some internal issues with the build system, the new input system is actually completely disabled in 2018.2 for Mac standalone builds.  (as you saw, does work in the editor)  I am working on getting this fix back-ported to both 2018.2 and 2018.3.  Will let you know on when this lands on a 2018.2 feature release and 2018.3 beta release.

**Comment by gmiot-poc** [comment]
Ok, thanks for your reply !

**Comment by douglas-piconi** [comment]
Fix submitted, will show up in 2018.2.9 release.
Has not made it to 2018.3 beta yet.
