### ISSUE TITLE
MyDevice is re-added every time entering play mode

### ISSUE THREAD

**Issue by borishsu** [Unity-Technologies/InputSystem#246]
I am trying to add a custom device and using `SimpleDevice.cs` in the package for testing. The code is shown below. I use `RuntimeInitializeOnLoadMethod` attribute to initialize the registration.

```csharp
[RuntimeInitializeOnLoadMethod]
public static void Initialize()
{
    InputSystem.RegisterLayout<MyDevice>();

    if (!InputSystem.devices.Any(x => x is MyDevice))
        InputSystem.AddDevice<MyDevice>();
}
```

However, the if statement doesn't seem to find any `MyDevice` in the system so a new one is added every time we enter play mode.

![2018-09-12 11_12_25](https://user-images.githubusercontent.com/38482575/45400179-b80fa380-b67d-11e8-93d3-a76f348cd6f6.png)

Is this a bug or did I miss something? Thanks.

**Comment by Rene-Damm** [comment]
This is a chicken-and-egg kind of problem. The system needs `InitializeOnLoad` code to run to have the up-to-date layout information in order to have all the layout information registered to be able to re-create devices it had before the domain reload (which happens when you enter play mode or change code) but the code above needs devices to have been restored already in order to work correctly.

Something that needs looking at.

The system used to take layout information across domain reloads and restore devices based on that information. However, aside from adding a great deal of data to domain reloads, it has the unfortunate side-effect of repeatedly recreating devices as `InitializeOnLoad` code was doing `RegisterLayout` calls.

**Comment by JiaUnity** [comment]
This does not happen on 0.2.0-preview and very obvious fixed in the past.
