### ISSUE TITLE
Editing SimpleDemo/SimpleControls error

### ISSUE THREAD

**Issue by iBicha** [Unity-Technologies/InputSystem#254]
Editing the asset `SimpleDemo/SimpleControls` throws this warning:

```
Unable to open Assets/Demo/SimpleDemo/SimpleControls.inputactions: Check external application preferences.
```
And this error:
```
InvalidCastException: Cannot cast from source type to destination type.
UnityEngine.Experimental.Input.Editor.InputActionImporterEditor.GetAsset () (at Packages/com.unity.inputsystem/InputSystem/Editor/InputActionImporterEditor.cs:54)
UnityEngine.Experimental.Input.Editor.InputActionImporterEditor.OnInspectorGUI () (at Packages/com.unity.inputsystem/InputSystem/Editor/InputActionImporterEditor.cs:21)
UnityEditor.InspectorWindow.DoOnInspectorGUI (Boolean rebuildOptimizedGUIBlock, UnityEditor.Editor editor, Boolean wasVisible, UnityEngine.Rect& contentRect) (at /Users/builduser/buildslave/unity/build/Editor/Mono/Inspector/InspectorWindow.cs:1599)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```

**Comment by Rene-Damm** [comment]
Turns out this is a bug in Unity's `ScriptedImporter` feature. A backport to 2018.2 of a fix is under way. 2018.3 should have the fix already.

What happens is that instead of putting the `InputActionAsset` object as the "main object" at the root of the asset, the import pipeline goes and randomly puts one of the `InputActionReference` subassets at the root.

Semi-related, as of https://github.com/Unity-Technologies/InputSystem/commit/872957d0737947d702d3feeea626f61f40537301, there's a change to allow double-clicking the individual action subassets instead of requiring the root asset to be double-clicked. This should also select the respective action in the editor window.

**Comment by Rene-Damm** [comment]
Should be fixed on head.

**Comment by aphongsamranNantG** [comment]
I am getting this error and it might be similar. I'm on Unity version **2019.1.6f1**. Input System Package version **0.2.10**.

As far as I can tell, I added the asset inputactions.asset file and generated the c# script file, performed testing to make sure it worked, added to source control (perforce), restarted Unity later and was unable to open my inputactions.asset file. Getting the errors below in the console.

```
InvalidCastException: Specified cast is not valid.
UnityEngine.InputSystem.Editor.InputActionImporterEditor.GetAsset () (at Library/PackageCache/com.unity.inputsystem@0.2.10-preview/InputSystem/Editor/AssetImporter/InputActionImporterEditor.cs:84)
UnityEngine.InputSystem.Editor.InputActionImporterEditor.OnInspectorGUI () (at Library/PackageCache/com.unity.inputsystem@0.2.10-preview/InputSystem/Editor/AssetImporter/InputActionImporterEditor.cs:42)
UnityEditor.UIElements.InspectorElement+<CreateIMGUIInspectorFromEditor>c__AnonStorey1.<>m__0 () (at C:/buildslave/unity/build/Editor/Mono/Inspector/InspectorElement.cs:462)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr)
```
