### ISSUE TITLE
Onscreen controls  do not work with bindings

### ISSUE THREAD

**Issue by douglas-piconi** [Unity-Technologies/InputSystem#286]
From Alec Larsens team

"Onscreen controls to work but if we include the bindings where there are axes bindings then they don't work"

**Comment by neonbevz** [comment]
Can you provide a more detailed description? Please include:
- Expected behavior
- Current Behavior
- Steps to reproduce

**Comment by dave24BG** [comment]
The issue was when an Input Action map had a binding with a composite DPad, no inputs would work on Android onScreen controls. 

Expected Behaviour: A single Input Action Map working across all platforms, with a DPad composite binding(WASD) along side a generic gamepad left/right stick for movement.  

Current Behaviour: Input only works on android when the DPad composite binding is removed. The onscreen control joystick will still move when you touch it, but it will not move the player.

Steps to reproduce, add an onscreen stick from prefabs into SimpleDemo.unity scene and set it to /<GamePad>/LeftStick, then build for android and try to walk around.

**Comment by douglas-piconi** [comment]
This appears to be the same problem on the spreadsheet.  Currently working on this fix.
