### ISSUE TITLE
Tap and hold actions over the same button are not disambiguated. Is it the expected behaviour? 

### ISSUE THREAD

**Issue by korut94** [Unity-Technologies/InputSystem#300]
Hi all, 
what I'm trying to do is when the `buttonEast` is tapped the player has to dodge, insted when the button is hold the player has to run. I created two `InputAction`s (DodgeAction and RunAction) and attached them to the relative functions as follow: 

```c#
DodgeAction.performed += _ => Dodge();
RunAction.started += _ => StartRun();
RunAction.performed += _ => StopRun();
```

Then in the inspector I bound the DodgeAction to the `buttonEast [Gamepad]` with `Tap` as interaction, and the RunAction to the `buttonEast [Gamepad]` but with `Hold` as interaction.

Now the problem is that when I press (or tap as well) the `buttonEast` both the function `Dodge()` and `StartRun()` are called. I get the same behaviour using `PressAndRelease` instead of `Hold` for the RunAction, furthermore `Hold` interaction does not allow to set the time that a button has to stay pressed to determine that it is hold.

Is it corret how I've done or I'm missing something? Thanks in advance.

**Comment by Rene-Damm** [comment]
I think the problem here is that `Hold` and when it triggers callbacks is confusing and need to be cleaned up.

`Hold` goes into `started` as soon as you press the button and triggers `performed` as soon as the hold is complete, i.e. once the button has been held down for more than the set duration (0.4 seconds by default).

This means that

>`DodgeAction.performed += _ => Dodge();`
>`RunAction.started += _ => StartRun();`
>`RunAction.performed += _ => StopRun();`

won't give you the effect you're looking for.

What you're trying to do here is how `Hold` probably *should* work. Or, similar to `Press` and `PressAndRelease`, maybe there should be a separate `HoldAndRelease` interaction. I'll give that a look.

Finally, you probably want `Tap` rather than `Press`. The thing is that you want the press to *not* register if it's long enough to qualify as a hold. `Press` doesn't care about how quick the press is and will thus always fire. `Tap` explicitly requires the press to be short.

**Comment by korut94** [comment]
Thanks @Rene-Damm for your quick reply! I solved using just one action binds to `PressAndRelease` and then the disambiguation between `Tap `and `Hold` event is performed by myself with a simple timer. The `HoldAndRelease` interaction would be really great ;)!

**Comment by Rene-Damm** [comment]
Closing as initial behavior was working as expected. Going over the interactions for consistency and completeness is in progress.
