### ISSUE TITLE
XInputController.current returns a Gamepad.  Should it return a XInputController?

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#31]

**Comment by Rene-Damm** [comment]
Yeah, think XInputController should probably implement its own .current getter.

**Comment by jackpr-unity** [comment]
![capture](https://user-images.githubusercontent.com/36174025/36331962-f2a3a3f4-1324-11e8-9a05-7cb6a417bff2.PNG)

It seems that you can get the current gamepad, but you have to check manually whether or not it is an XInput device?  This enables our paradigm of writing input code against an abstracted interface, but does it make writing device specific code more difficult?

**Comment by Rene-Damm** [comment]
Not sure what you mean. The static getter here is defined in Gamepad. Writing 'XInputController.current' will simply do the same as 'Gamepad.current' which is why the refactor is suggested. Not sure every device class should have its own getter (for DualShockGamepadHID, for example, it doesn't make sense IMO) but for XInputController, it seems to make sense to add its own static getter.

**Comment by jackpr-unity** [comment]
I mean writing code against Gamepad is "better" in most instances, but writing against XInputController may be necessary for people wanting to target certain specific XInput device capabilities.

**Comment by douglas-piconi** [comment]
@jackpr-unity take a look at my PR https://github.com/Unity-Technologies/InputSystem/pull/416    will this help you with this problem at all?
