### ISSUE TITLE
[iOS][Touch] Events get more rare on "older" touches when having multiple touches

### ISSUE THREAD

**Issue by renaldasrep** [Unity-Technologies/InputSystem#344]
Found using 0.0.12-preview

How to reproduce:
1. Move one finger on the screen position is updated precisely (floating point values)
2. Add another finger and move them together
3. Notice that now, the "older" touch (the first finger that was laid upon touchscreen (e.g. indexed 0))
isn't updated as precise (whole number values), but the "later" one (e.g. indexed 1) is still precise.

Also touches get stuck (release events are skipped?)

Does not reproduce on Android

**Comment by todi1856** [comment]
Assign to me, alternatively it's reproducible in https://github.com/24BitGames/TouchInputSamples

**Comment by todi1856** [comment]
@Rene-Damm This seems like a bug in managed side, I'll try to make a test, but here's a snapshot from debug build, where I print what I send from native, and what we receive on managed

NewInput: Touch Began 2163.000000 x 963.000000, id = 5, time = 24.335799
Touch Began (2163.0, 963.0) 5
Touch Stationary (2163.0, 963.0) 5
NewInput: Touch Began 1792.000122 x 885.000000, id = 6, time = 24.361293
Touch Began (1792.0, 885.0) 6
NewInput: Touch Moved 2173.000000 x 975.000000, id = 5, time = 24.386364
NewInput: Touch Moved 2178.000000 x 982.000000, id = 5, time = 24.394971
NewInput: Touch Moved 1804.000000 x 907.000000, id = 6, time = 24.394969
Touch Began (1792.0, 885.0) 6
Touch Moved (2173.0, 975.0) 5
Touch Moved (2178.0, 982.0) 5
Touch Stationary (2178.0, 982.0) 5
NewInput: Touch Moved 2188.000000 x 1002.000000, id = 5, time = 24.411497
NewInput: Touch Moved 1809.000000 x 928.000000, id = 6, time = 24.411497
NewInput: Touch Moved 2202.000000 x 1038.000000, id = 5, time = 24.428161
NewInput: Touch Moved 1818.000000 x 960.000000, id = 6, time = 24.428159
Touch Moved (2188.0, 1002.0) 5
Touch Moved (2202.0, 1038.0) 5
Touch Stationary (2202.0, 1038.0) 5
NewInput: Touch Moved 2220.000000 x 1116.000000, id = 5, time = 24.452731
NewInput: Touch Moved 1827.000000 x 1041.000000, id = 6, time = 24.452731
NewInput: Touch Moved 2223.000000 x 1146.000000, id = 5, time = 24.461670
NewInput: Touch Moved 1828.000000 x 1080.000000, id = 6, time = 24.461669
Touch Moved (2220.0, 1116.0) 5
Touch Moved (2223.0, 1146.0) 5
NewInput: Touch Moved 2227.000000 x 1214.000000, id = 5, time = 24.478610
NewInput: Touch Moved 1828.000000 x 1156.000000, id = 6, time = 24.478610
NewInput: Touch Moved 2227.000000 x 1290.000000, id = 5, time = 24.494703
NewInput: Touch Moved 1818.000000 x 1231.000000, id = 6, time = 24.494702
Touch Moved (2223.0, 1146.0) 5
Touch Moved (2227.0, 1214.0) 5
Touch Moved (2227.0, 1290.0) 5


Notice last 7 lines, touch with id 6 has lower timestamp, I think this is why it's being ignored


NewInput: Touch Moved 2227.000000 x 1214.000000, id = 5, time = 24.478610
NewInput: Touch Moved 1828.000000 x 1156.000000, id = 6, time = 24.478610
NewInput: Touch Moved 2227.000000 x 1290.000000, id = 5, time = 24.494703
NewInput: Touch Moved 1818.000000 x 1231.000000, id = 6, time = 24.494702 <--- IGNORED because previous event was sent with timestamp 24.494703
Touch Moved (2223.0, 1146.0) 5
Touch Moved (2227.0, 1214.0) 5
Touch Moved (2227.0, 1290.0) 5

**Comment by renaldasrep** [comment]
Can no longer reproduce
