### ISSUE TITLE
Automatic binding constantly reads scroll wheel

### ISSUE THREAD

**Issue by Baste-RainGames** [Unity-Technologies/InputSystem#383]
Gif:

![scroll](https://user-images.githubusercontent.com/12800067/51426906-2ac2f980-1bf1-11e9-9858-090715041d0b.gif)

The action has type "Any". Pretty much instantly after I click the rebind button, it picks up a scroll wheel input. I'm not scrolling my mouse wheel, and no other programs are behaving like I'm scrolling, so it's _probably_ not a hardware issue. 

If I set the action to a type that doesn't support scrolling, this doesn't happen.

**Comment by fnuecke** [comment]
Same issue here, 0.1.2-preview on Unity 2018.3.2f1, Windows 10, Logitech G700s.

Also noticed that when opening the mouse in the input debugger (Window/Input Debug, double-click on Mouse) `scroll.y` will jump to non-zero when moving the mouse (pos or neg depending on last scroll direction it seems). Value changes rapidly, but absolute value *might* be correlated to cursor delta (i.e. faster cursor movement seems to lead to larger absolute `scroll.y` values).

Edit: this also happens when in play mode, looks like scroll is fired whenever some other mouse change happens (movement, button clicks).

**Comment by mwnDK1402** [comment]
I'm getting the same problem. 0.2.1-preview on Unity 2018.3.9f1, Windows 10, Logitech G703.

Edit: I thought this might be something with Logitech mice, but @Wokarol got the same bug with a different mouse.

**Comment by Wokarol** [comment]
Also "ScrollVertical [Any]" return 1 for each LMB press (Win 10, preview-0.2.6, Unity 2019.1.0b8)

**Comment by JiaUnity** [comment]
Closing. Tracked here: https://issuetracker.unity3d.com/issues/ui-when-using-detect-input-to-bind-an-action-the-mouse-scroll-is-picked-up-automatically
