### ISSUE TITLE
[XR] Can't Get Oculus Rift to track

### ISSUE THREAD

**Issue by IKnowBashFu** [Unity-Technologies/InputSystem#400]
Using the tracked pose driver from the new input system, I have my head tracking set up as such:
![Image of Unity Tracked Pose Driver settings](https://img.bashfu.nyc/o3rf8or3xvoiedu.png)

The rift HMD doesn't actually track, unless I've done something wrong. The camera works fine without a pose controller on it, but then stops working once I add it on. This applies to the touch controllers as well.

**Comment by RoboSkyrat** [comment]
I'm currently working on the same project as @IKnowBashFu and I've discovered that if the Game window isn't in focus the HMD doesn't track at all.

**Comment by IKnowBashFu** [comment]
So with that solved, I guess the question now is, can we ignore application focus so that this isn't an issue? I can see problems down the road if a user has a window randomly steal focus. It would be very disorienting.

**Comment by StayTalm** [comment]
You can, but it is brand new and in the process of being backported:
In 2019.1 (beta 1 is out now), and using the 0.1.2-preview version of the New Input System you can use `InputSystem.runInBackground = true;`
And you will continue to receive events regardless of focus.  This works for XR devices, and for other devices based on what the underlying OS supports (e.g. OSX will not give us mouse data out of focus, but windows will).

**Comment by StayTalm** [comment]
Sorry, I think I just gave some frustrating advice.
2019.1.0b1 will not work with 0.1.2-preview, because there was a core unity API change.  2019.1.0b1 is the first version to have the runInBackground toggle, so it's somewhat jammed up.
There is a 0.1.3-preview coming soon fixing the API mismatch, or if you feel crafty, the error line itself can be manually editted (a function parameter was dropped and the naming should be pretty intuitive).

**Comment by IKnowBashFu** [comment]
Thanks for the great answer. I appreciate the help, and I think we'll wait for the backport, since we want at least some stability in our project, haha.
