### ISSUE TITLE
Dpad bindings not readable, but Vector2 bound to Dpad works.

### ISSUE THREAD

**Issue by danielheim** [Unity-Technologies/InputSystem#438]
As per my [report](https://forum.unity.com/threads/input-system-update.508660/page-9#post-4235749) in the forums...

Dpad values are not readable when bound directly.
However if I bind Dpad direction to a composite Vector2 binding, it works as expected.

Testing on Unity 2018.3.6f1 on Mac with InputSystem v0.2.0-preview from Package Manager. Testing input via wired DualShock 4 and XBox 360 controllers.
[Sample .inputactions and MonoBehaviour attached](https://github.com/Unity-Technologies/InputSystem/files/2922753/Archive.zip).
You will notice logs come through from Vector2 binding, but nothing from the direct binding.

**Comment by danielheim** [comment]
This appears to be fixed now in v2.6.0-preview (Unity 2019.1.0b8). Thanks to much!

However, If I add a "Press" interaction to the binding, I only seem to be able to get one successful press from the input, and nothing further.

**Comment by JiaUnity** [comment]
@danielheim Glad the bug is fixed.
About the "Press" interaction, if the option "Press and Release" only trigger the action once, it is a known bug and you can track it here: https://issuetracker.unity3d.com/issues/ui-press-and-release-for-press-interaction-does-not-trigger-action-on-release
It should be fixed in future release. 
If you have other issues, feel free to file a bug through Bug Reporter in Editor, so a minimal repro project can be attached, which will help us to identify the issue. 
Thanks!
