### ISSUE TITLE
Wrong asset type in inspector

### ISSUE THREAD

**Issue by Wokarol** [Unity-Technologies/InputSystem#498]
Every Input Action Asset type shows as "Input Action Asset" in inpector, why is that?
`[SerializeField] MyMap map;` shows as `Map    None (Input Action Asset)` instead of `Map    None (MyMap)`

**Comment by Rene-Damm** [comment]
Ah yup, that could be refined. The reason is that the custom inspector for the `InputActionAssetReference` here (i.e. `MyMap`) simply reuses the property inspector for `InputActionAsset` underneath. That's where the text is coming from.

On latest head, we've redone part of how the whole setup works. Now, the generated class no longer represents a reference to the asset but rather *contains* the asset. This means that you no longer have to drag the .inputactions asset manually onto the slot of the generated asset. With this change,`InputActionAssetReference` is gone along with the custom inspector that prints the text above.
