### ISSUE TITLE
Xbox Controller

### ISSUE THREAD

**Issue by jonny2027** [Unity-Technologies/InputSystem#52]
Hi,

Will this work with a standard Xbox Controller on a Xbox development Kit out the box?

Thanks
Jonathan

**Comment by Rene-Damm** [comment]
Yes, the Xbox One controller on the Xbox (including extra paddle buttons of the Elite controller and trigger motor rumbles) is supported out of the box.

https://github.com/Unity-Technologies/InputSystem/blob/develop/Packages/com.unity.inputsystem/InputSystem/Plugins/XInput/XboxOneGamepad.cs

**Comment by jonny2027** [comment]
Absolutely fantastic :-) Going to give this a look tonight. I wish Microsoft would release XDK plugin support for betas so I could test it on the device. Great work. Thank you

**Comment by Rene-Damm** [comment]
Thank you :)

Please note that the current develop branch cannot unfortunately be run with the 2018.1 beta as 2018.1 doesn't have the required native changes. We're pushing hard for the 2018.2 to have most of the native changes in place so that everyone can run the InputSystem with a public Unity build.

**Comment by jonny2027** [comment]
Oh right so this wont work in the 2018.1b12 version and will requite a beta of 2018.2. No problem. I will wait for that release :-)

**Comment by Rene-Damm** [comment]
Ok cool :)
