### ISSUE TITLE
Feature Request: Make the input control UI columns adjustable width

### ISSUE THREAD

**Issue by VR-Architect** [Unity-Technologies/InputSystem#520]
The Action Maps column and Action column could be narrower so we have a bigger Properties column. Because we can't adjust the width, there is a horizontal scroll bar on the Properties column which is not an optimal user experience. 

Thanks for the consideration.

**Comment by Rene-Damm** [comment]
Yup, agree that having draggable splitters would be great.

The horizontal scrollbar appearing on "Properties" is mostly a bug, though. At least when the bar appears after selecting a processor or interaction. The UI layout code for some reason gets the width wrong and thus makes the entire UI wider instead of sticking to the current width. Something to be fixed.

**Comment by Rene-Damm** [comment]
Migrated the request to our internal tracking system so it's guaranteed to make the round into our considerations for what to do after 1.0 is in safe waters. (internal ticket ISX-271)

As part of us migrating away from GitHub issues, I'll go close this one. But no worries, doesn't mean it's forgotten :)
