### ISSUE TITLE
When creating action sets, the "Add Action" button is at the bottom of an action set, but the new action is created at the top of the list

### ISSUE THREAD

**Issue by jackpr-unity** [Unity-Technologies/InputSystem#55]
When creating a large action set this causes a lot of scrolling back and forth.  It would be a nice enhancement to create a new action right next to the <Add Action...> button.

**Comment by Rene-Damm** [comment]
Yeah, it's a bug somewhere in the UI code. If you create more than one action, a previously created action suddenly jumps to the right place at the bottom.

There's tons of issues in the current action set editor. I've started today to at least address some. This issue here as well as some of the bigger ones will likely not get addressed, though, until we have the full UI pass which will likely re-implement some of the UIs entirely.
