### ISSUE TITLE
SendMessages() with playerinput module, how to send cancelled?

### ISSUE THREAD

**Issue by JamhammerRob** [Unity-Technologies/InputSystem#736]
Currently I have a method say, OnMove() that triggers my playermovement, but if I have a stick down when I pause the game, the player continues to move since apparently the inputvalue value hasn't been set to zero. I am not sure where to set that to zero, or maybe a bug?

```
    public void OnMove(InputValue value)
    {
        movement = value.Get<Vector2>();
    }

    private void Update()
    {
        Vector2 m = new Vector2(movement.x, movement.y) * 10f * Time.deltaTime;
        transform.Translate(m, Space.World);
    }

    public void OnPause()
    {
        playerInput.SwitchCurrentActionMap("UI");
    }
```

Thanks!

**Comment by mikemassari** [comment]
I would like to know as well please

**Comment by Rene-Damm** [comment]
Valid issue. With the action type of "Move" set to "Value", there should be a call when the action is disabled and thus cancelled. However, the problem is that ATM `InputValue.Get<T>` will *always* return the current value of the control which means that even though you do get a call on cancelled, you still get a non-default value because the stick is actuated. And yeah, without the callback context, you have no way to work around it.

I'm thinking that when something does `InputAction.CallbackContext.ReadValue<T>` (which `InputValue.Get<T>` does underneath) on an action that's cancelled, it should probably return `default(T)`. Let me look into that. May have some implications that I'm not seeing ATM.

For the moment, I suggest switching from messages to events and checking for `InputAction.CallbackContext.canceled` explicitly as a workaround.
