### ISSUE TITLE
Multiple Gamepads cross triggering

### ISSUE THREAD

**Issue by randompast** [Unity-Technologies/InputSystem#742]
# Versions
Unity 2019.3.0a10
Input System 0.9.0
Gamepad Device F310

## Goal
Local Multiplayer attempted via device.id.

## Issue
Gamepad.current.id registered the prior controller before switching back.

## Method
- Create Input Action PlayerControls
- Make Action Map "main"
- Make Action "getID"
- Make event binding -> "buttonSouth"
- Save -> Generate Script
- Create Controls.cs
```
    PlayerControls controls;
    void Awake(){
        controls = new PlayerControls();
        controls.main.getID.performed += ctx => Debug.Log(Gamepad.current.id);
    }
```
- Attach Controls.cs to a scene's game object.
- Plug in two controllers A and B
- Play Scene

1. Hit A.buttonSouth -> A.id, Hit A.buttonSouth -> A.id, ...
2. Hit **B**.buttonSouth -> **A.id**, Hit B.buttonSouth -> B.id, ...
3. Hit **A**.buttonSouth -> **B.id**, Hit A.buttonSouth -> A.id, ...

The problem behavior is seen in steps 2 and 3.  The "Window -> Analysis -> Input Debugger" displayed the correct device id unlike Gamepad.current.id.  Likely there's a better approach than using the device id this way.

**Comment by Rene-Damm** [comment]
ATM this is expected behavior. `MakeCurrent` on the device is triggered after state processing (which includes action processing) has finished.

Having `MakeCurrent` happen in-between probably is more desirable overall but it would require some code shuffling and I'm not sure it's a big enough issue to warrant that the change.

>Likely there's a better approach than using the device id this way.

You can grab the device directly from the callback.

```
    PlayerControls controls;
    void Awake(){
        controls = new PlayerControls();
        controls.main.getID.performed += ctx => Debug.Log(ctx.control.device.id);
    }
```
