### ISSUE TITLE
Difficulty with control scheme switching

### ISSUE THREAD

**Issue by CptOblivion** [Unity-Technologies/InputSystem#764]
I split Mouse and Keyboard into separate control schemes (mainly so I can hide the cursor and the pointer-type selection when navigating menus with the keyboard, and so I can disable arrow navigation of menus when the mouse is being used). For the most part this works, except moving the mouse doesn't cause the control scheme to switch to Mouse, I have to click somewhere on the screen. I've attached the inputactions file, in case that's helpful.
[ControlsMap.zip](https://github.com/Unity-Technologies/InputSystem/files/3484281/ControlsMap.zip)

**Comment by Rene-Damm** [comment]
Thank you for filing the ticket and attaching the file. Can confirm that indeed I'm seeing the same problem. Digging in, I can see that `InputUser.OnDeviceStateChange` -- which is meant to detect when an unpaired device is used -- is (incorrectly) filtering out the state change on the delta control because of how it checks the magnitude of actuation on the control. Will fix.

**Comment by Rene-Damm** [comment]
Fixed by #781.
