### ISSUE TITLE
Collapse/Expand all items in the hierarchy

### ISSUE THREAD

**Issue by perrauo** [Unity-Technologies/InputSystem#812]
I having an issue using the action map editor where all items are expanded whenever I open the editor. You must understand that with very large number of items this becomes quickly unmanageable.  I suggest either a shortcut or a menu option which collapses/expands all menu items at the same time to avoid manually closing everything.

Thanks

![image](https://user-images.githubusercontent.com/24371247/63866224-e961ac00-c980-11e9-8d11-719cae9db11f.png)

![image](https://user-images.githubusercontent.com/24371247/63866953-0f3b8080-c982-11e9-80b9-5f95f8645f94.png)

**Comment by Rene-Damm** [comment]
Yup, makes sense. The tree view control has a built-in mechanism to collapse and expand entire branches by alt-clicking but I'm not aware of a shortcut for collapsing/expanding siblings. Normally, you can alt-click the root and then expand it normally to get that effect but with the action tree view not showing a root, that won't work.

I noted it down. (Internal ticket: ISX-268)

We're in the process of migrating all our bug tracking to the official Unity bug tracking system (which gives us the benefit of properly integrating ourselves with Unity QA procedures) and turn off GitHub issue tracking once done so I'll be closing the issue here. No worries, doesn't mean it's forgotten. We have it recorded.
