### ISSUE TITLE
Support for mice with more than 5 buttons

### ISSUE THREAD

**Issue by JimmyCushnie** [Unity-Technologies/InputSystem#822]
The old input system had support for mice with up to 7 buttons; `KeyCode` went from `Mouse0` to `Mouse6`. The new input system, however, has

* leftButton
* rightButton
* middleButton
* forwardButton
* backButton

Only 5 buttons. Can we get support for many-buttoned mice like [this one](https://www.corsair.com/us/en/p/CH-9304011-NA)?

**Comment by Rene-Damm** [comment]
Yup, I put it on the list for >1.0.

RE the old system: Its 7 button support in the old input system was often more theoretical in nature. On Windows, for example, input will still only be reported on the first 5 buttons.

We're in the process of migrating all our bug/issue tracking to the official Unity bug tracking system (which gives us the benefit of properly integrating ourselves with Unity QA procedures) and turn off GitHub issue tracking once done. I'll be closing the issue here. But no worries, it's noted down and not forgotten.

(Internal ticket: ISX-267)

**Comment by petersvp** [comment]
Just to add to this, @Rene-Damm these mice actually come with Keyboard HID driver so... ^^ It's essentially a keyboard device AND a mouse device. Razer Naga Trinity for example is same concept.

**Comment by SpiritWolf2015** [comment]
Not support for mice with more than 5 buttons in new input system version 1.4.1!! Where is the unity issues url??
