### ISSUE TITLE
[Gamepad] If using Gamepad/dpad in an action set, all buttons generate noise for that InputAction

### ISSUE THREAD

**Issue by periodyctom** [Unity-Technologies/InputSystem#85]
Commit 7948ead, Win10 64, 2018.2b1
XBOX One Controller, XBOX 360 Controller (both USB).

Repro 5/5

If Gamepad/dpad is used for an action input (to say, drive movement) ANY Button will cause it to fire events (at least 2-3). This includes buttons already assigned to other InputActions, and buttons that are not assigned to any InputAction.

**Comment by Rene-Damm** [comment]
Hmm, have to think about that one. In a way, it's by design. Actions have no idea about the mechanics of a control. If there's no modifier, they simply trigger whenever the control state changes. To get more differentiated triggering, modifiers have to be added.

A related problem is that ATM if you bind a button, the action triggers once on button press and once on button release (any value change triggers the action). You have to add a press modifier to get what would intuitively seems expected default behavior.

Not sure yet how to best handle that. Making dpads work as expected can be done with a modifier but the core of the problem remains.

**Comment by periodyctom** [comment]
With the recent changes to the API, this isn't an issue any more. Do you want to go ahead and close this?
