### ISSUE TITLE
Would like Switch Pro Controller to work natively 

### ISSUE THREAD

**Issue by DavidT76** [Unity-Technologies/InputSystem#852]
I know that when you connect the Nintendo Switch Pro Controller to a Windows PC or Laptop, Unity sees what Windows sees and currently no input is registered by Windows or Unity unless I have Valve's Steam app open and then Windows and by extension Unity registers input from the Switch Pro Controller (This only the case when the Switch Pro Controller connected with a wired connection only; connecting with Bluetooth seems fine).

**Comment by DavidT76** [comment]
I realize that the heading I choose for the description is poor choice of words. The Switch Pro Controller does work natively when connected via Bluetooth but not with a wired only connection.

**Comment by Rene-Damm** [comment]
Thanks for reporting. We'll take a look.

We're in the process of migrating all our bug tracking to the official Unity bug tracking system (which gives us the benefit of properly integrating ourselves with Unity QA procedures) and turn off GitHub issue tracking once done. I've migrated the case over to FogBugz.

FB Ticket: 1190216
Unity Issue Tracker: https://issuetracker.unity3d.com/product/unity/issues/guid/1190216/

Closing the issue here. No worries, doesn't mean it's forgotten :)
