### ISSUE TITLE
0.9.6 - PlayerInputManager does not create second player when using reference

### ISSUE THREAD

**Issue by JamhammerRob** [Unity-Technologies/InputSystem#856]
Unless i'm doing something incorrectly, when I try and have a player join using the reference above, the first player successfully gets instantiated, but it seemingly stops receiving the event on the second attempt. I can switch between controllers and have either one work one first player creation, but the second always fails. There is no error code. My input asset is below.

![image](https://user-images.githubusercontent.com/12954767/64828875-212f3d00-d598-11e9-946c-5169aa2d54f5.png)

![image](https://user-images.githubusercontent.com/12954767/64828941-5b004380-d598-11e9-8440-13ffcf6c40f8.png)

When I change the reference to "any" button press, it works as it should. Multiple players are created and given their respective controller. The code below.

![image](https://user-images.githubusercontent.com/12954767/64829057-bdf1da80-d598-11e9-96a7-2d7017051cd4.png)

**Comment by Djaymare** [comment]
We are using the main InputActionAsset to hold the reference. We should always instantiate InputActionAsset in this case. See here :
https://github.com/Djaymare/InputSystem/blob/eeaf61c3cc3410ae974599a7fa4e5f54a5f0a9c5/Packages/com.unity.inputsystem/InputSystem/Plugins/PlayerInput/PlayerInput.cs#L862

**Comment by Rene-Damm** [comment]
Hey @Djaymare, sorry for the huge lag here.

The problem here is an unfortunate side-effect of how `PlayerInput` currently handles actions and something we should deal with more robustly.

To explain, `PlayerInput` currently duplicates the actions it is given only when it deems that necessary. Which is as soon as there is more than one player in the game. Meaning that player number 1 will always end up with the original set of actions linked to it.

So what happens is that as soon as the first player joins, it makes the given actions its own. Including the join action. And then no one else can join.

Means that ATM, to use "Join Players When Join Action Is Triggered", the given action must *not* belong to the set of actions that is also used by `PlayerInput`. This is counter-intuitive, cumbersome, and, well, error-prone.

We'll take a look at making that more robust.

For now, splitting out the join action (e.g. by disabling "Use Reference" and setting it up directly on `PlayerInputManager`) should fix the problem.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
