### ISSUE TITLE
PointerEventData.delta value is smaller than expected

### ISSUE THREAD

**Issue by ersankavafoglu** [Unity-Technologies/InputSystem#877]
I was porting my old dragging code to the new input system and noticed that the PointerEventData.delta value is smaller than the actual displacement. That results in an accumulative position error(displacement) from the expected since I'm adding delta to the UI element each frame. I'm sure that my code is correct because it works properly with Unity.Input . I both tested in editor and in android. Both have faulty values while in android the error is noticeably greater (maybe 2x). As a note EnhancedTouchSupport is enabled.

**Comment by Rene-Damm** [comment]
Thank you for reporting. We'll take a look.

We're in the process of migrating all our bug tracking to the official Unity bug tracking system (which gives us the benefit of properly integrating ourselves with Unity QA procedures) and turn off GitHub issue tracking once done. I've migrated the case over to FogBugz.

FB Ticket: 1189902
Unity Issue Tracker: https://issuetracker.unity3d.com/product/unity/issues/guid/1189902/

Closing the issue here. No worries, doesn't mean it's forgotten :)
