### ISSUE TITLE
Cant completely disable old input system

### ISSUE THREAD

**Issue by rotter** [Unity-Technologies/InputSystem#893]
I am trying to migrate my game to the new input system, but I cant seem to find a way to completely disable and break the compilation on parts that are using the old input system.

The old code stops working when I disable it on Player Settings, but it doesnt give me compilation errors, so Im going crazy finding countless bugs on my game, and certainly I will forget some things and will break something for some players.

My suggestion is that if one sets "Active Input Handling: Input System (preview)", that should completely remove the old library and make the code stop compiling, so we know where/what to fix.

**Comment by Rene-Damm** [comment]
Ah yes, so...... bit of an unfortunate thing. What we've done is add code to 2019.3+ to address this. From that version forward, if you select "Input System" as your "Active Input Handling" in the player settings and someone is using the old input system APIs, you get an error in the console. Which sounds like what you're looking for. But with it being in 2019.3, that probably doesn't help you :/

That change should probably have been there since 2019.1 but when we finally made it, that train was already gone.

>My suggestion is that if one sets "Active Input Handling: Input System (preview)", that should completely remove the old library and make the code stop compiling, so we know where/what to fix.

Unfortunately, that's probably not feasible. The problem is that there's tons of packages (asset store and UPM) that would fail to compile and that, as a user of those packages, would be hard to fix. But the presence of *some* old input code doesn't necessarily mean the package as a whole isn't useful. 

We've recently added an `#define` that allows `#if`ing out code when the new input system is used but my assumption is the ecosystem will take quite a while to adapt.

The error on 2019.3 is hopefully a reasonable first step.

**Comment by rotter** [comment]
Thanks for the reply. The change on 2019.3 should probably help me already. But regarding completely disabling the old input code, it makes sense it would break tons of things, but since if you set the input system to the new one the old input calls will stop working, does it make any sense to let it compile but not work? This sounds to me as an enormous source of untrackable/hidden bugs.

On my project I ended up setting it to "Both" instead of enabling the new input system only, but that doesnt feel like a permanent solution.

**Comment by rotter** [comment]
As a second suggestion, maybe add a fourth "Active Input Handling" selection: "Active Input Handling: Input System - Break Old Input". This way if someone wants to track down all the code (at least on his own project) that uses the old input he can do so, and then change the input back to "Both" or "Input System" to make the code compile again (in case third party libs are using it).

This also allows the devs to report incompatibility on third party libs they are using (without breaking the compilation it would be very hard/impossible to tell).

Obs: depending on how the 2019.3 console warning thing works this may not be needed. But if it's runtime it will not pick all the execution paths, while a compilation switch will certainly show all usage points.

**Comment by Rene-Damm** [comment]
When we'll tackle the next step of deprecating the old system (the first step was just the error when you switch to the new one), I think it makes sense to take a look at how we can help guide the transition better. A fourth option could be one way. Though my thinking is more along the lines of allowing you to take the module that contains the old input system bindings (which is already separate in the Unity runtime) out of the build. AFAIK (disclaimer: haven't tried myself) that option actually already exists. From all I know, it's possible to suppress specific engine modules from Packages/manifest.json. BUT... don't quote me on that :) Still, ideally something like that would allow anyone to simply take the old input system out of the compilation and force compile errors.

**Comment by popcron** [comment]
@rotter You could potentially use a roslyn analyzer in your project to detect the use of the old input system and throw an error on those lines.

**Comment by stefanunity** [comment]
Hello,

we're going to close all the github issues and will concentrate bug information in the Unity public issue tracker https://issuetracker.unity3d.com/product/unity/issues?project=116&status=1&unity_version=&view=hottest.

If you are still experienceing this issue in the latest package version please do file a bug report as described here https://unity3d.com/unity/qa/bug-reporting
For general feedback and discussions you can go to https://forum.unity.com/forums/new-input-system.103/

Thank you!
