### ISSUE TITLE
Support remote hardware control

### ISSUE THREAD

**Issue by shitake2333** [Unity-Technologies/InputSystem#894]
Now the hardware layer of the input system supports different local hardware inputs and add multiple InputPlayer components for developing local multiplayer game.

Why don't we support  remote hardware input to make online multiplayer development as easy as a local multiplayer game?

**Comment by Rene-Damm** [comment]
The input system itself has a remoting layer (`InputRemoting`) which is used by the input debugger to remote input from players. ATM `InputRemoting` is probably still missing some public APIs to allow implementing custom transport layers but even without `InputRemoting` it's pretty straightforward to build your own remoting. I'm aware of one team, for example, building a web streaming solution and remoting input through the new input system.

**Comment by Rene-Damm** [comment]
PSA: We're in the process of migrating all our bug tracking to the official Unity bug tracking system (which gives us the benefit of properly integrating ourselves with Unity QA procedures) and turn off GitHub issue tracking once done.

This issue here is probably best handled as a discussion on the forum.
