### ISSUE TITLE
No name added with AddCompositeBinding()

### ISSUE THREAD

**Issue by sstrong2** [Unity-Technologies/InputSystem#895]
When a composite binding is added to an action, the name of the binding is not set. This leads to issues with the asset editor.

`UnityEngine.InputSystem.InputActionSetupExtensions.AddCompositeBinding(action, "Dpad")
  .With("Up", "<Keyboard>/e", "Keyboard&Mouse")
  .With("Down", "<Keyboard>/q", "Keyboard&Mouse")
  .With("Left", "<Keyboard>/rightArrow", "Keyboard&Mouse")
  .With("Right", "<Keyboard>/leftArrow", "Keyboard&Mouse");`

**Comment by Rene-Damm** [comment]
Thank you for reporting. We'll take a look.

We're in the process of migrating all our bug tracking to the official Unity bug tracking system (which gives us the benefit of properly integrating ourselves with Unity QA procedures) and turn off GitHub issue tracking once done. I've migrated the case over to FogBugz.

FB Ticket: 1189879
Unity Issue Tracker: https://issuetracker.unity3d.com/product/unity/issues/guid/1189879/

Closing the issue here. No worries, doesn't mean it's forgotten :)
