### ISSUE TITLE
Actions not enabled after auto-switching control scheme

### ISSUE THREAD

**Issue by kakysha** [Unity-Technologies/InputSystem#900]
So I have multiple control schemes (kb+mouse, gamepad), along with multiple actions for each device, but there is one action (rotate) only for gamepad right stick, cause mouse rotation are handled through code. So when I start my game, Input System recognizes its currently kb+mouse control scheme (configured `<Any>` for default control scheme on PlayerInput) and disables that one `rotate` action, so when I try to use gamepad everything works except rotation.
Debugger shows that the game auto-switching schemes, but do not enables back the actions which it disabled for previous scheme.

**Comment by Rene-Damm** [comment]
Thank you for reporting. We'll take a look. If `rotate` remains disabled, that's definitely buggy.

We're in the process of migrating all our bug tracking to the official Unity bug tracking system (which gives us the benefit of properly integrating ourselves with Unity QA procedures) and turn off GitHub issue tracking once done. I've migrated the case over to FogBugz.

FB Ticket: 1189867
Unity Issue Tracker: https://issuetracker.unity3d.com/product/unity/issues/guid/1189867/

Closing the issue here. No worries, doesn't mean it's forgotten :)
