### ISSUE TITLE
Generated C# class does not escape all uses of action names

### ISSUE THREAD

**Issue by BlkCatGmg** [Unity-Technologies/InputSystem#901]
If in the InputActionAsset you type "return" as an action it will create an error for every "," in the generated script. What I'm saying is... you can't use the word "return" in the action map.

**Comment by Rene-Damm** [comment]
Indeed, while some pieces of the code generator correctly escape the action names as `@actionName` (that's why the `return` getter isn't causing an action), some pieces don't. Thanks for reporting.

**Comment by Rene-Damm** [comment]
We're in the process of migrating all our bug tracking to the official Unity bug tracking system (which gives us the benefit of properly integrating ourselves with Unity QA procedures) and turn off GitHub issue tracking once done. I've migrated the case over to FogBugz.

FB Ticket: 1189861
Unity Issue Tracker: https://issuetracker.unity3d.com/product/unity/issues/guid/1189861/

Closing the issue here. No worries, doesn't mean it's forgotten :)
