### ISSUE TITLE
Pause button not mapped for iOS gamepads

### ISSUE THREAD

**Issue by m4ff** [Unity-Technologies/InputSystem#903]
With the legacy input manager the pause button for iOS gamepads is mapped to `joystick button 0` (https://docs.unity3d.com/Manual/iphone-joystick.html). Currently there is no way to bind an action to that button using the new input system.

**Comment by Rene-Damm** [comment]
The GameController's pause button on iOS is mapped to `Gamepad.startButton`.

Note that because of peculiarities of the GameController API which only gives us press notification but no corresponding release notification (see https://developer.apple.com/documentation/gamecontroller/gccontroller/1458852-controllerpausedhandler), there will be two events for each single pause button press. An event containing the press immediately followed by an event containing a release. In effect, this means that the press will not be visible in the debugger. However, actions will see the value change so binding to the start button should correctly trigger.
